before_install:
- rvm uninstall jruby
- rvm use jruby-1.7.18 --install
- export JRUBY_OPTS=--dev
language: ruby
jdk:
- oraclejdk7
rvm:
- jruby-1.7.18
script: bundle exec rake spec && (bundle exec rake release || echo "Not released")
deploy:
  provider: rubygems
  api_key:
    secure: I9uNSIU6Ob+UlxXzSdUnzg9YVT8tsZULQwYDd0ENLrTE1CdCDiShw7oXP3AYAr/SOQg8yrURkNIW0QV5h4nKoZb+rGpZBMyY9wTtFpek4daYNRJKxUsrFX/Jv84zjqEO/AFEwTtlVKhpUOcCOp26bdCVaBaFgJMZPcObmm7z2bc=
  gem: pacer
  on:
    branch: master
    repo: pangloss/pacer
